### ISSUE TITLE
Phpswitch should check source tarball integrity

### ISSUE THREAD

**Issue by lyrixx** [jubianchi/phpswitch#20]
use case:
1.  install 5.4.3
2. CTRL + C
3.  install 5.4.3 => fails because the tarball is incomplete.

**Comment by jubianchi** [comment]
:+1: I will add this feature asap!

**Comment by lyrixx** [comment]
I don't need this feature anymore. Closing the issue.

**Comment by jubianchi** [comment]
i think nobody needs such a bugged piece software.

Unfortunately I don't have time to maintain it. And to be honest I think nobody uses it.

Thanks for closing ;)

**Comment by lyrixx** [comment]
No problem ;)
I made a big [github cleanup](https://github.com/lyrixx?tab=activity)
