### ISSUE TITLE
HomeBrew integration

### ISSUE THREAD

**Issue by shulard** [jubianchi/phpswitch#25]
I use **HomeBrew** for my Mac configuration and tools updates but I think **phpswitch** is a tools that I need.
Have you ever think to make your installer compatible with a tool like that ?

Your installer script is a little too standalone to be connected with this kind of use.

**Comment by jubianchi** [comment]
Hi!

I could publish a homebrew formula to ease phpswitch install but, to be fair, this is not my priority : first I would like to make phpswitch stable, fix some bugs here and there and then, spend some time on integrating it with other tools.

**Comment by shulard** [comment]
Hi,

Ok I understand and I think too that make formula on unstable version is not a really good idea... Have you a roadmap ? You tell that there are bugs, are they referenced somewhere? I will be happy to give help :)

**Comment by jubianchi** [comment]
@shulard I'm working on a roadmap and I'll publish it in the form of issues here.

**Comment by shulard** [comment]
Ok, let me know when it's done i will check if i can help...
