### ISSUE TITLE
.phpswithrc is missing in my home folder :D

### ISSUE THREAD

**Issue by thehawk970** [jubianchi/phpswitch#3]

**Comment by jubianchi** [comment]
It's not anymore in the home directory.
Now, when you install phpswitch, you have to use the `init` command so it creates its workspace in its installation folder.

Then, the `.phpswitchrc` and `.phpswitchprompt` files are in this folder ;)

I need to add something to be able to easily change this behavior.

**Comment by thehawk970** [comment]
I am not read the readme , its explain ;)
Thanks
